### ISSUE TITLE
主页第三章链接错误

### ISSUE THREAD

**Issue by Tianyu000** [CoxxA/bitcoin-ahr999-HODL#4]
[主页(/docs/README.md)](https://github.com/CoxxA/bitcoin-ahr999-HODL/blob/master/docs/README.md) -入门-第三章《囤比特币：你离财富自由还有多远？》链接错误(/docs/di-er-san) 404 NOT FOUND，正确链接应为：/docs/di-san-zhang

**Comment by CoxxA** [comment]
谢谢提醒，修复好了~
